# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- none

pool:
  vmImage: ubuntu-latest

container:
  image: armcontainerregistry01.azurecr.io:dotnetsdk
  endpoint: containerRegistry

variables:
  solution: '**/*.sln'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: CmdLine@2
  inputs:
    script: |
      dotnet restore
      dotnet build

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CmdLine@2
  displayName: Docker commands
  inputs:
    script: |
      docker login --username parteg132 --password $XD
      docker build . -t parteg132/booking-api-azure-session16
      docker image push parteg132/booking-api-azure-session16
  env:
    XD: $(DOCKER_PASS) 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
